import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
	return [
		{
			url: 'https://mtlbaljam.org/fr',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 1,
		},
		{
			url: 'https://mtlbaljam.org/en',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 1,
		},
		{
			url: 'https://mtlbaljam.org/en/2026/competitions',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/en/2026/extra',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/en/2026/instructors',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/en/2026/music',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/en/2026/registration',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/en/2026/tracks',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/en/2026/venue',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/fr/2026/competitions',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/fr/2026/extra',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/fr/2026/instructors',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/fr/2026/music',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/fr/2026/registration',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/fr/2026/tracks',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/fr/2026/venue',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/fr/2025/instructors',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/en/2025/instructors',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/fr/2025/registration',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/en/2025/registration',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/fr/2025/tracks',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/en/2025/tracks',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/fr/2025/schedule',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/en/2025/schedule',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/fr/2025/competitions',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/en/2025/competitions',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/fr/2025/venue',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/en/2025/venue',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/fr/2025/extra',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/en/2025/extra',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/fr/2024/music',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/en/2024/music',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/fr/2024/venue',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/en/2024/venue',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/fr/about',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/en/about',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/fr/2024/instructors',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/en/2024/instructors',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/fr/2024/extra',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/en/2024/extra',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/fr/2024/competitions',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/en/2024/competitions',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/fr/code-of-conduct',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/en/code-of-conduct',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/fr/2024/registration',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/en/2024/registration',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/fr/volunteering',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/en/volunteering',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/fr/travel',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/en/travel',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/fr/visiting',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
		{
			url: 'https://mtlbaljam.org/en/visiting',
			lastModified: new Date(),
			changeFrequency: 'weekly',
			priority: 0.7,
		},
	]
}
